// <auto-generated />
using System;
using FutureStepsAcademy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureStepsAcademy.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251012064658_..")]
    partial class _
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutureStepsAcademy.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseID = 1,
                            CourseCode = "CS101",
                            courseName = "Introduction to Programming"
                        },
                        new
                        {
                            CourseID = 2,
                            CourseCode = "CS102",
                            courseName = "Data Structures"
                        },
                        new
                        {
                            CourseID = 3,
                            CourseCode = "CS201",
                            courseName = "Algorithms"
                        },
                        new
                        {
                            CourseID = 4,
                            CourseCode = "IT101",
                            courseName = "Networking Basics"
                        },
                        new
                        {
                            CourseID = 5,
                            CourseCode = "IT102",
                            courseName = "Database Systems"
                        },
                        new
                        {
                            CourseID = 6,
                            CourseCode = "IT201",
                            courseName = "Web Development"
                        },
                        new
                        {
                            CourseID = 7,
                            CourseCode = "SE101",
                            courseName = "Software Requirements"
                        },
                        new
                        {
                            CourseID = 8,
                            CourseCode = "SE102",
                            courseName = "Software Design Patterns"
                        },
                        new
                        {
                            CourseID = 9,
                            CourseCode = "SE201",
                            courseName = "Agile Methodologies"
                        },
                        new
                        {
                            CourseID = 10,
                            CourseCode = "EE101",
                            courseName = "Circuit Analysis"
                        },
                        new
                        {
                            CourseID = 11,
                            CourseCode = "EE102",
                            courseName = "Electromagnetics"
                        },
                        new
                        {
                            CourseID = 12,
                            CourseCode = "EE201",
                            courseName = "Digital Systems"
                        },
                        new
                        {
                            CourseID = 13,
                            CourseCode = "ME101",
                            courseName = "Thermodynamics"
                        },
                        new
                        {
                            CourseID = 14,
                            CourseCode = "ME102",
                            courseName = "Fluid Mechanics"
                        },
                        new
                        {
                            CourseID = 15,
                            CourseCode = "ME201",
                            courseName = "Machine Design"
                        },
                        new
                        {
                            CourseID = 16,
                            CourseCode = "CE101",
                            courseName = "Structural Analysis"
                        },
                        new
                        {
                            CourseID = 17,
                            CourseCode = "CE102",
                            courseName = "Construction Materials"
                        },
                        new
                        {
                            CourseID = 18,
                            CourseCode = "CE201",
                            courseName = "Transportation Engineering"
                        },
                        new
                        {
                            CourseID = 19,
                            CourseCode = "BA101",
                            courseName = "Principles of Management"
                        },
                        new
                        {
                            CourseID = 20,
                            CourseCode = "BA102",
                            courseName = "Marketing Fundamentals"
                        },
                        new
                        {
                            CourseID = 21,
                            CourseCode = "BA201",
                            courseName = "Financial Accounting"
                        },
                        new
                        {
                            CourseID = 22,
                            CourseCode = "EC101",
                            courseName = "Microeconomics"
                        },
                        new
                        {
                            CourseID = 23,
                            CourseCode = "EC102",
                            courseName = "Macroeconomics"
                        },
                        new
                        {
                            CourseID = 24,
                            CourseCode = "EC201",
                            courseName = "Econometrics"
                        },
                        new
                        {
                            CourseID = 25,
                            CourseCode = "MA101",
                            courseName = "Calculus I"
                        },
                        new
                        {
                            CourseID = 26,
                            CourseCode = "MA102",
                            courseName = "Linear Algebra"
                        },
                        new
                        {
                            CourseID = 27,
                            CourseCode = "MA201",
                            courseName = "Discrete Mathematics"
                        },
                        new
                        {
                            CourseID = 28,
                            CourseCode = "PH101",
                            courseName = "Classical Mechanics"
                        },
                        new
                        {
                            CourseID = 29,
                            CourseCode = "PH102",
                            courseName = "Electromagnetism"
                        },
                        new
                        {
                            CourseID = 30,
                            CourseCode = "PH201",
                            courseName = "Quantum Physics"
                        });
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Course_Department", b =>
                {
                    b.Property<int>("Course_DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Course_DepartmentID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.HasKey("Course_DepartmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Course_Departments");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentName = "Computer Science",
                            Department_Code = "CS01"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentName = "Information Technology",
                            Department_Code = "IT02"
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentName = "Software Engineering",
                            Department_Code = "SE03"
                        },
                        new
                        {
                            DepartmentID = 4,
                            DepartmentName = "Electrical Engineering",
                            Department_Code = "EE04"
                        },
                        new
                        {
                            DepartmentID = 5,
                            DepartmentName = "Mechanical Engineering",
                            Department_Code = "ME05"
                        },
                        new
                        {
                            DepartmentID = 6,
                            DepartmentName = "Civil Engineering",
                            Department_Code = "CE06"
                        },
                        new
                        {
                            DepartmentID = 7,
                            DepartmentName = "Business Administration",
                            Department_Code = "BA07"
                        },
                        new
                        {
                            DepartmentID = 8,
                            DepartmentName = "Economics",
                            Department_Code = "EC08"
                        },
                        new
                        {
                            DepartmentID = 9,
                            DepartmentName = "Mathematics",
                            Department_Code = "MA09"
                        },
                        new
                        {
                            DepartmentID = 10,
                            DepartmentName = "Physics",
                            Department_Code = "PH10"
                        });
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateRecorded")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeType")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("GradeID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeID = 1,
                            CourseID = 1,
                            DateRecorded = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 85m,
                            StudentID = 1
                        },
                        new
                        {
                            GradeID = 2,
                            CourseID = 1,
                            DateRecorded = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 90m,
                            StudentID = 1
                        },
                        new
                        {
                            GradeID = 3,
                            CourseID = 1,
                            DateRecorded = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 1,
                            Score = 88m,
                            StudentID = 1
                        },
                        new
                        {
                            GradeID = 4,
                            CourseID = 2,
                            DateRecorded = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 78m,
                            StudentID = 1
                        },
                        new
                        {
                            GradeID = 5,
                            CourseID = 2,
                            DateRecorded = new DateTime(2024, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 82m,
                            StudentID = 1
                        },
                        new
                        {
                            GradeID = 6,
                            CourseID = 4,
                            DateRecorded = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 92m,
                            StudentID = 2
                        },
                        new
                        {
                            GradeID = 7,
                            CourseID = 4,
                            DateRecorded = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 95m,
                            StudentID = 2
                        },
                        new
                        {
                            GradeID = 8,
                            CourseID = 5,
                            DateRecorded = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 2,
                            Score = 89m,
                            StudentID = 2
                        },
                        new
                        {
                            GradeID = 9,
                            CourseID = 5,
                            DateRecorded = new DateTime(2024, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 91m,
                            StudentID = 2
                        },
                        new
                        {
                            GradeID = 10,
                            CourseID = 7,
                            DateRecorded = new DateTime(2024, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 87m,
                            StudentID = 3
                        },
                        new
                        {
                            GradeID = 11,
                            CourseID = 7,
                            DateRecorded = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 93m,
                            StudentID = 3
                        },
                        new
                        {
                            GradeID = 12,
                            CourseID = 8,
                            DateRecorded = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 5,
                            Score = 95m,
                            StudentID = 3
                        },
                        new
                        {
                            GradeID = 13,
                            CourseID = 8,
                            DateRecorded = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 90m,
                            StudentID = 3
                        },
                        new
                        {
                            GradeID = 14,
                            CourseID = 10,
                            DateRecorded = new DateTime(2024, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 75m,
                            StudentID = 4
                        },
                        new
                        {
                            GradeID = 15,
                            CourseID = 10,
                            DateRecorded = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 80m,
                            StudentID = 4
                        },
                        new
                        {
                            GradeID = 16,
                            CourseID = 11,
                            DateRecorded = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 1,
                            Score = 72m,
                            StudentID = 4
                        },
                        new
                        {
                            GradeID = 17,
                            CourseID = 11,
                            DateRecorded = new DateTime(2024, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 78m,
                            StudentID = 4
                        },
                        new
                        {
                            GradeID = 18,
                            CourseID = 13,
                            DateRecorded = new DateTime(2024, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 88m,
                            StudentID = 5
                        },
                        new
                        {
                            GradeID = 19,
                            CourseID = 13,
                            DateRecorded = new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 92m,
                            StudentID = 5
                        },
                        new
                        {
                            GradeID = 20,
                            CourseID = 14,
                            DateRecorded = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 2,
                            Score = 85m,
                            StudentID = 5
                        },
                        new
                        {
                            GradeID = 21,
                            CourseID = 16,
                            DateRecorded = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 90m,
                            StudentID = 6
                        },
                        new
                        {
                            GradeID = 22,
                            CourseID = 16,
                            DateRecorded = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 94m,
                            StudentID = 6
                        },
                        new
                        {
                            GradeID = 23,
                            CourseID = 17,
                            DateRecorded = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 1,
                            Score = 86m,
                            StudentID = 6
                        },
                        new
                        {
                            GradeID = 24,
                            CourseID = 19,
                            DateRecorded = new DateTime(2024, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 91m,
                            StudentID = 7
                        },
                        new
                        {
                            GradeID = 25,
                            CourseID = 19,
                            DateRecorded = new DateTime(2024, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 96m,
                            StudentID = 7
                        },
                        new
                        {
                            GradeID = 26,
                            CourseID = 20,
                            DateRecorded = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 6,
                            Score = 100m,
                            StudentID = 7
                        },
                        new
                        {
                            GradeID = 27,
                            CourseID = 22,
                            DateRecorded = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 83m,
                            StudentID = 8
                        },
                        new
                        {
                            GradeID = 28,
                            CourseID = 22,
                            DateRecorded = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 87m,
                            StudentID = 8
                        },
                        new
                        {
                            GradeID = 29,
                            CourseID = 23,
                            DateRecorded = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 2,
                            Score = 80m,
                            StudentID = 8
                        },
                        new
                        {
                            GradeID = 30,
                            CourseID = 25,
                            DateRecorded = new DateTime(2024, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 95m,
                            StudentID = 9
                        },
                        new
                        {
                            GradeID = 31,
                            CourseID = 25,
                            DateRecorded = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 98m,
                            StudentID = 9
                        },
                        new
                        {
                            GradeID = 32,
                            CourseID = 26,
                            DateRecorded = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 1,
                            Score = 92m,
                            StudentID = 9
                        },
                        new
                        {
                            GradeID = 33,
                            CourseID = 28,
                            DateRecorded = new DateTime(2024, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 84m,
                            StudentID = 10
                        },
                        new
                        {
                            GradeID = 34,
                            CourseID = 28,
                            DateRecorded = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 88m,
                            StudentID = 10
                        },
                        new
                        {
                            GradeID = 35,
                            CourseID = 29,
                            DateRecorded = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 5,
                            Score = 90m,
                            StudentID = 10
                        },
                        new
                        {
                            GradeID = 36,
                            CourseID = 4,
                            DateRecorded = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 3,
                            Score = 89m,
                            StudentID = 11
                        },
                        new
                        {
                            GradeID = 37,
                            CourseID = 4,
                            DateRecorded = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 93m,
                            StudentID = 11
                        },
                        new
                        {
                            GradeID = 38,
                            CourseID = 5,
                            DateRecorded = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 2,
                            Score = 87m,
                            StudentID = 11
                        },
                        new
                        {
                            GradeID = 39,
                            CourseID = 6,
                            DateRecorded = new DateTime(2024, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 1,
                            Score = 91m,
                            StudentID = 11
                        },
                        new
                        {
                            GradeID = 40,
                            CourseID = 6,
                            DateRecorded = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GradeType = 4,
                            Score = 94m,
                            StudentID = 11
                        });
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 1,
                            FirstName = "Abdurrahman",
                            LastName = "Nassani",
                            Phone = "+905538866317",
                            Year = "FrishMan"
                        },
                        new
                        {
                            StudentID = 2,
                            Address = "Istanbul/Turkey",
                            DepartmentID = 2,
                            FirstName = "Omar",
                            LastName = "Hassan",
                            Phone = "+905311112233",
                            Year = "Sophomore"
                        },
                        new
                        {
                            StudentID = 3,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 3,
                            FirstName = "Lina",
                            LastName = "Khaled",
                            Phone = "+905322223344",
                            Year = "Junior"
                        },
                        new
                        {
                            StudentID = 4,
                            Address = "Ankara/Turkey",
                            DepartmentID = 4,
                            FirstName = "Ahmad",
                            LastName = "Mahmoud",
                            Phone = "+905333334455",
                            Year = "Senior"
                        },
                        new
                        {
                            StudentID = 5,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 5,
                            FirstName = "Sara",
                            LastName = "Youssef",
                            Phone = "+905344445566",
                            Year = "Freshman"
                        },
                        new
                        {
                            StudentID = 6,
                            Address = "Izmir/Turkey",
                            DepartmentID = 6,
                            FirstName = "Khaled",
                            LastName = "Othman",
                            Phone = "+905355556677",
                            Year = "Sophomore"
                        },
                        new
                        {
                            StudentID = 7,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 7,
                            FirstName = "Mariam",
                            LastName = "Salem",
                            Phone = "+905366667788",
                            Year = "Junior"
                        },
                        new
                        {
                            StudentID = 8,
                            Address = "Antalya/Turkey",
                            DepartmentID = 8,
                            FirstName = "Tariq",
                            LastName = "Ali",
                            Phone = "+905377778899",
                            Year = "Senior"
                        },
                        new
                        {
                            StudentID = 9,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 9,
                            FirstName = "Noor",
                            LastName = "Rahman",
                            Phone = "+905388889900",
                            Year = "Freshman"
                        },
                        new
                        {
                            StudentID = 10,
                            Address = "Mersin/Turkey",
                            DepartmentID = 10,
                            FirstName = "Hadi",
                            LastName = "Fouad",
                            Phone = "+905399991122",
                            Year = "Sophomore"
                        },
                        new
                        {
                            StudentID = 11,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 2,
                            FirstName = "Aya",
                            LastName = "Samir",
                            Phone = "+905300002233",
                            Year = "Junior"
                        });
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student_Course", b =>
                {
                    b.Property<int>("Student_CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Student_CourseID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("Student_CourseID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StudentID");

                    b.ToTable("Student_Courses");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("TeacherID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherID = 1,
                            Address = "Istanbul/Turkey",
                            DepartmentID = 1,
                            Email = "ahmed.ali@example.com",
                            FirstName = "Ahmed",
                            HireDate = new DateOnly(2015, 3, 1),
                            LastName = "Ali",
                            Phone = "+905300000001",
                            Salary = 4000f
                        },
                        new
                        {
                            TeacherID = 2,
                            Address = "Ankara/Turkey",
                            DepartmentID = 2,
                            Email = "lina.khaled@example.com",
                            FirstName = "Lina",
                            HireDate = new DateOnly(2016, 5, 15),
                            LastName = "Khaled",
                            Phone = "+905300000002",
                            Salary = 4200f
                        },
                        new
                        {
                            TeacherID = 3,
                            Address = "Izmir/Turkey",
                            DepartmentID = 3,
                            Email = "omar.hassan@example.com",
                            FirstName = "Omar",
                            HireDate = new DateOnly(2017, 8, 10),
                            LastName = "Hassan",
                            Phone = "+905300000003",
                            Salary = 4100f
                        },
                        new
                        {
                            TeacherID = 4,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 4,
                            Email = "sara.youssef@example.com",
                            FirstName = "Sara",
                            HireDate = new DateOnly(2018, 2, 20),
                            LastName = "Youssef",
                            Phone = "+905300000004",
                            Salary = 4300f
                        },
                        new
                        {
                            TeacherID = 5,
                            Address = "Antalya/Turkey",
                            DepartmentID = 5,
                            Email = "khaled.othman@example.com",
                            FirstName = "Khaled",
                            HireDate = new DateOnly(2019, 7, 5),
                            LastName = "Othman",
                            Phone = "+905300000005",
                            Salary = 4500f
                        },
                        new
                        {
                            TeacherID = 6,
                            Address = "Bursa/Turkey",
                            DepartmentID = 6,
                            Email = "mariam.salem@example.com",
                            FirstName = "Mariam",
                            HireDate = new DateOnly(2015, 11, 12),
                            LastName = "Salem",
                            Phone = "+905300000006",
                            Salary = 4400f
                        },
                        new
                        {
                            TeacherID = 7,
                            Address = "Mersin/Turkey",
                            DepartmentID = 7,
                            Email = "tariq.ali@example.com",
                            FirstName = "Tariq",
                            HireDate = new DateOnly(2020, 1, 25),
                            LastName = "Ali",
                            Phone = "+905300000007",
                            Salary = 4600f
                        },
                        new
                        {
                            TeacherID = 8,
                            Address = "Adana/Turkey",
                            DepartmentID = 8,
                            Email = "noor.rahman@example.com",
                            FirstName = "Noor",
                            HireDate = new DateOnly(2014, 9, 17),
                            LastName = "Rahman",
                            Phone = "+905300000008",
                            Salary = 4700f
                        },
                        new
                        {
                            TeacherID = 9,
                            Address = "Konya/Turkey",
                            DepartmentID = 9,
                            Email = "hadi.fouad@example.com",
                            FirstName = "Hadi",
                            HireDate = new DateOnly(2016, 12, 3),
                            LastName = "Fouad",
                            Phone = "+905300000009",
                            Salary = 4800f
                        },
                        new
                        {
                            TeacherID = 10,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 10,
                            Email = "aya.samir@example.com",
                            FirstName = "Aya",
                            HireDate = new DateOnly(2017, 4, 28),
                            LastName = "Samir",
                            Phone = "+905300000010",
                            Salary = 4900f
                        });
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Teacher_Course", b =>
                {
                    b.Property<int>("Teacher_CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Teacher_CourseID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.HasKey("Teacher_CourseID");

                    b.HasIndex("CourseID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Teacher_Courses");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Course_Department", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Course", "course")
                        .WithMany("course_Departments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureStepsAcademy.Models.Department", "department")
                        .WithMany("Course_Departments")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("department");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Grade", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureStepsAcademy.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Payment", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId");

                    b.HasOne("FutureStepsAcademy.Models.Teacher", "Teacher")
                        .WithMany("Payments")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Department", "department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student_Course", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Course", "course")
                        .WithMany("student_Courses")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureStepsAcademy.Models.Student", "student")
                        .WithMany("student_Courses")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("student");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Teacher", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Department", "department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Teacher_Course", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Course", "course")
                        .WithMany("teacher_Courses")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureStepsAcademy.Models.Teacher", "teacher")
                        .WithMany("teacher_Courses")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Course", b =>
                {
                    b.Navigation("course_Departments");

                    b.Navigation("student_Courses");

                    b.Navigation("teacher_Courses");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Department", b =>
                {
                    b.Navigation("Course_Departments");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Payments");

                    b.Navigation("student_Courses");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Teacher", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("teacher_Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
