// <auto-generated />
using System;
using FutureStepsAcademy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureStepsAcademy.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250919110557_add database ")]
    partial class adddatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutureStepsAcademy.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentName = "Computer Science",
                            Department_Code = "CS01"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentName = "Information Technology",
                            Department_Code = "IT02"
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentName = "Software Engineering",
                            Department_Code = "SE03"
                        },
                        new
                        {
                            DepartmentID = 4,
                            DepartmentName = "Electrical Engineering",
                            Department_Code = "EE04"
                        },
                        new
                        {
                            DepartmentID = 5,
                            DepartmentName = "Mechanical Engineering",
                            Department_Code = "ME05"
                        },
                        new
                        {
                            DepartmentID = 6,
                            DepartmentName = "Civil Engineering",
                            Department_Code = "CE06"
                        },
                        new
                        {
                            DepartmentID = 7,
                            DepartmentName = "Business Administration",
                            Department_Code = "BA07"
                        },
                        new
                        {
                            DepartmentID = 8,
                            DepartmentName = "Economics",
                            Department_Code = "EC08"
                        },
                        new
                        {
                            DepartmentID = 9,
                            DepartmentName = "Mathematics",
                            Department_Code = "MA09"
                        },
                        new
                        {
                            DepartmentID = 10,
                            DepartmentName = "Physics",
                            Department_Code = "PH10"
                        });
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 1,
                            FirstName = "Abdurrahman",
                            LastName = "Nassani",
                            Phone = "+905538866317",
                            Year = "FrishMan"
                        },
                        new
                        {
                            StudentID = 2,
                            Address = "Istanbul/Turkey",
                            DepartmentID = 2,
                            FirstName = "Omar",
                            LastName = "Hassan",
                            Phone = "+905311112233",
                            Year = "Sophomore"
                        },
                        new
                        {
                            StudentID = 3,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 3,
                            FirstName = "Lina",
                            LastName = "Khaled",
                            Phone = "+905322223344",
                            Year = "Junior"
                        },
                        new
                        {
                            StudentID = 4,
                            Address = "Ankara/Turkey",
                            DepartmentID = 4,
                            FirstName = "Ahmad",
                            LastName = "Mahmoud",
                            Phone = "+905333334455",
                            Year = "Senior"
                        },
                        new
                        {
                            StudentID = 5,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 5,
                            FirstName = "Sara",
                            LastName = "Youssef",
                            Phone = "+905344445566",
                            Year = "Freshman"
                        },
                        new
                        {
                            StudentID = 6,
                            Address = "Izmir/Turkey",
                            DepartmentID = 6,
                            FirstName = "Khaled",
                            LastName = "Othman",
                            Phone = "+905355556677",
                            Year = "Sophomore"
                        },
                        new
                        {
                            StudentID = 7,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 7,
                            FirstName = "Mariam",
                            LastName = "Salem",
                            Phone = "+905366667788",
                            Year = "Junior"
                        },
                        new
                        {
                            StudentID = 8,
                            Address = "Antalya/Turkey",
                            DepartmentID = 8,
                            FirstName = "Tariq",
                            LastName = "Ali",
                            Phone = "+905377778899",
                            Year = "Senior"
                        },
                        new
                        {
                            StudentID = 9,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 9,
                            FirstName = "Noor",
                            LastName = "Rahman",
                            Phone = "+905388889900",
                            Year = "Freshman"
                        },
                        new
                        {
                            StudentID = 10,
                            Address = "Mersin/Turkey",
                            DepartmentID = 10,
                            FirstName = "Hadi",
                            LastName = "Fouad",
                            Phone = "+905399991122",
                            Year = "Sophomore"
                        },
                        new
                        {
                            StudentID = 11,
                            Address = "Gaziantep/Turkey",
                            DepartmentID = 2,
                            FirstName = "Aya",
                            LastName = "Samir",
                            Phone = "+905300002233",
                            Year = "Junior"
                        });
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student_Teacher", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.Property<int>("Student_TeacherID")
                        .HasColumnType("int");

                    b.HasKey("StudentID", "TeacherID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Student_Teachers");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("TeacherID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student_Teacher", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Student", "student")
                        .WithMany("student_Teachers")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureStepsAcademy.Models.Teacher", "teacher")
                        .WithMany("student_Teachers")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Teacher", b =>
                {
                    b.HasOne("FutureStepsAcademy.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Student", b =>
                {
                    b.Navigation("student_Teachers");
                });

            modelBuilder.Entity("FutureStepsAcademy.Models.Teacher", b =>
                {
                    b.Navigation("student_Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
